import { CharactersCard } from "@/components";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

export default function EpisodeProfile() {
  const router = useRouter();
  const [data, setData] = useState({});

  useEffect(() => {
    fetch(`https://rickandmortyapi.com/api/episode/${router.query.pid}`)
      .then((res) => res.json())
      .then(async (res) => {
        console.log('in')
        if (res.characters?.length) {
          console.log(res.episode)
          await fetch(
            `https://rickandmortyapi.com/api/character/${res.characters
                .map((characters) => characters.split("/").pop())
                .join(",")}`
          )
            .then((res) => res.json())
            .then((characters) => (res.characters = characters));
        }

        return res;
      })
      .then((res) => setData(res));
  }, []);

  console.log(data);

  return (
    <>
      <Head>
        <title>{data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ display: "flex", flexDirection: "column"}}>
        <h1>{data.name}</h1>
        <h2>{data.air_date}</h2>
        <div style={{ display: "grid", gridColumn: 2, gap: "50px" }}>
          <div style={{ display: "flex", flexDirection: "column"}}>
            <h3>Cast</h3>
          </div>
            {data.characters?.map((characters) => (
              <Link key={characters.id} href={`/characters/${characters.id}`}>
                <CharactersCard
                  name={characters.name}
                  species={characters.species}
                  image={characters.image}
                />
              </Link>
            ))}
          </div>
      </main>
    </>
  );
}
