import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Episode } from "../../components/episode-card";

export default function Episodes() {
const [data, setData] = useState([]);
const [info, setInfo] = useState();
const [searchValue, setSearchValue] = useState("");
const [page, setPage] = useState(1);

useEffect(() => {
  fetch(`https://rickandmortyapi.com/api/episode/?page=${page}`)
    .then((res) => res.json())
    .then((res) => {
      setData((prev) => [...prev, ...res.results]);
      setInfo(res.info);
    });
}, [page]);

useEffect(() => {
  fetch(`https://rickandmortyapi.com/api/episode/?name=${searchValue}`)
    .then((res) => res.json())
    .then((res) => {
      setData(res.results);
      setInfo(res.info);
    });
  }, [searchValue]);

  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input
        value={searchValue}
        onChange={(e) => setSearchValue(e.target.value)}
      />
      <div style={{ display: 'grid', gap: '50px' }}>
        {data.map((episode) => (
          <Link href={`/episodes/${episode.id}`} key={episode.id}>
            <Episode
              name={episode.name}
              date={episode.air_date}
              idNum={episode.episode}
            />
          </Link>
        ))}
      </div>

      {info?.next && (
        <button onClick={() => setPage((prev) => ++prev)}>LOAD MORE</button>
      )}
    </>
  );
}
